version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.90.0
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local_files:/files

volumes:
  n8n_data: